filter:
  vertical_zones:
    - start: 0.0
      end: 0.25
      downsample: 4  # Upper 25% of rows, keep 1/4
    - start: 0.25
      end: 0.75
      downsample: 1  # Middle 50%, keep all
    - start: 0.75
      end: 1.0
      downsample: 4  # Lower 25%, keep 1/4