pointcloud_filter_node:
  ros__parameters:
    input_topic: "/lidar/points"
    output_topic: "/lidar/filtered"
    y_rotation_angle: -0.1570796 
    x_traslation: 0.
    y_traslation: 0.
    z_traslation: 1.
    gradient: true
    intensity: false
    vertical_zones:
      - "start: 0.0, end: 0.325, downsample: 12"
      - "start: 0.325, end: 0.525, downsample: 5"
      - "start: 0.525, end: 1.0, downsample: 8"
